import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const regis = localFont({
	src: "./fonts/regis/Regis-Semibold.ttf",
	variable: "--font-regis",
	weight: "100 900",
});
const silka = localFont({
	src: "./fonts/silka/Silka-Regular.otf",
	variable: "--font-silka",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${regis.variable} ${silka.variable} antialiased`}>
				{children}
			</body>
		</html>
	);
}
